name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

env:
  REGISTRY_LOGIN: ${{ secrets.REGISTRY_LOGIN }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  ENV: ${{ secrets.DEV_ENV }}

jobs:
  build:
    name: Build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        run: docker login -u $REGISTRY_LOGIN -p $REGISTRY_PASSWORD

      - name: Build Docker image
        run: |
          IMAGE_NAME=$REGISTRY_LOGIN/${{vars.REPO_NAME}}:${{ github.sha }}
          printf "%s" "$ENV" >> .env
          printf "%s" "$ENV"
          docker build . -t $IMAGE_NAME
          docker push $IMAGE_NAME

  test:
    name: Test
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        run: echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_LOGIN -p $REGISTRY_PASSWORD

      - name: Pull Docker image
        run: |
          IMAGE_NAME=$REGISTRY_LOGIN/${{vars.REPO_NAME}}:${{ github.sha }}
          docker pull $IMAGE_NAME
          docker run $IMAGE_NAME php artisan test

