name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

env:
  REGISTRY_LOGIN: ${{ vars.REGISTRY_LOGIN }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  ENV: ${{ secrets.DEV_ENV }}
  SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
  SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
  SERVER_IP: ${{ secrets.SERVER_IP }}
  COMPOSE_PATH: ${{ vars.COMPOSE_PATH }}
  REPO_NAME: ${{ vars.REPO_NAME }}

jobs:
  build:
    name: Build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        run: docker login -u $REGISTRY_LOGIN -p $REGISTRY_PASSWORD

      - name: Build Docker image
        run: |
          IMAGE_NAME=$REGISTRY_LOGIN/$REPO_NAME:${{ github.sha }}
          printf "%s" "$ENV" >> .env
          docker build . -t $IMAGE_NAME
          docker push $IMAGE_NAME

  test:
    name: Test
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        run: echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_LOGIN -p $REGISTRY_PASSWORD

      - name: Pull Docker image
        run: |
          IMAGE_NAME=$REGISTRY_LOGIN/$REPO_NAME:${{ github.sha }}
          docker pull $IMAGE_NAME
          docker run $IMAGE_NAME php artisan test || (echo "Tests failed" && docker rmi $IMAGE_NAME && exit 1)

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy with Docker Compose
        run: |
          ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa <<<y >/dev/null 2>&1
          ssh-copy-id -i ~/.ssh/id_rsa.pub ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} -i ${{ secrets.SERVER_SSH_KEY }} "cd  $COMPOSE_PATH && docker-compose pull && docker-compose up -d"

